# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Julia B. Chan
email:  jchan@cironline.org
description: > # this means to ignore newlines until "baseurl:"
  Journalist + Digital creative


baseurl:  "" # the subpath of your site, e.g. /blog
url:      "" # the base hostname & protocol for your site

twitter_username:       juliachanb
github_username:        juliachanb
linkedin_username:      juliachanb
google_plus_username:   
facebook_username:      

# Build settings
markdown: kramdown
